sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-881383183980"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

